### PR TITLE
fix: Fixes incorrect order of array_replace_recursive arguments & other issues

### LINKED ISSUE #431: [CMSP-467] Please don't strip all tags from the cache password.
Thanks for developing such a great plugin and maintaining it.

I noticed a bug: commenting it out helped:

                                        'auth' => isset( $_SERVER['CACHE_PASSWORD'] ) ? /*wp_strip_all_tags(*/ $_SERVER['CACHE_PASSWORD']/* )*/ : '',

ERRORS:
[1] This corrupts our passwords and authentication fails. 
[2] If the CACHE_PASSWORD is provided as a user+pw pair, WP errors that it needs a string.

Thanks for looking into this.
Dennis

### LINKED ISSUE #432: [CMSP-470] Replace use of wp_strip_all_tags (possibly any wp filter function?) in object-cache.php
From [WordPress.org support](https://wordpress.org/support/topic/fatal-error-when-combining-with-full-page-cache/) (cc @mdifelice)

----
## Fatal error when combining with full-page cache
Since version 1.4.2 (at least that I am aware of), the method build_client_parameters included in the object-cache.php has been modified to escape the server configuration variables using the function wp_strip_all_tags.

If this plugin is used in conjunction with the WordPress full-page cache functionality it throws a fatal error. The reason is that in order to activate that functionality WordPress includes the file advanced-cache.php before the file wp-includes/formatting.php is included (which is in charge of defining wp_strip_all_tags). If advanced-cache.php uses object caching it must include object-cache.php but when executing the mentioned method a fatal error is raised. And if formatting.php is included or the missing function is defined somehow before it is called, a fatal error will be raised later because of a duplicate definition.

I would like to know if this is something you plan to fix in an upcoming version because, if you do not, I would need to replace the plugin. I think that probably what you want to achieve with that change can be easily achieved with a built-in PHP function, as strip_tags maybe.

----
Another regression/bug introduced with #400.
Also tagging as related (as also affected by `wp_strip_all_tags`) #431

### LINKED ISSUE #433: Changes Merged from #360 Break Redis Connections on Pantheon Due to #400 and Incorrect array_replace_recursive call
After further testing there with Pantheon after the merge of changes in #360 to resolve those caused by #400 it was discovered that there was an error in the usage of `array_replace_recursive()`. (Noted: https://github.com/pantheon-systems/wp-redis/pull/360#issuecomment-1590055893) I updated a Gist with a patch that fixes this, however, this should be applied here before the next release otherwise it will break all Object Caching on Pantheon sites that deploy the plugin.

### PR DESCRIPTION
**Pull request by timnolte**
* Fixes #433
* Fixes #432 
* Fixes #431
* Further clean-up & standardization between object-cache.php & wp-redis.php.
* Fixes incorrect order of array_replace_recursive arguments.
* Addresses issue with port still not being null for socket connections due to defaults array_repalce_recursive use.

### CODE REVIEW

**Comment by timnolte** [comment]
Ah, looks like PHPCS is unhappy, though really it is incorrectly unhappy. I'll try to resolve those linting issues.

File: object-cache.php [hunk 1]
```diff
@@ -1247,10 +1247,11 @@ public function build_client_parameters( $redis_server ) {
 			// Attempt to automatically load Pantheon's Redis config from the env.
 			if ( isset( $_SERVER['CACHE_HOST'] ) ) {
 				$redis_server = [
-					'host' => wp_strip_all_tags( $_SERVER['CACHE_HOST'] ),
-					'port' => isset( $_SERVER['CACHE_PORT'] ) ? wp_strip_all_tags( $_SERVER['CACHE_PORT'] ) : $port,
-					'auth' => isset( $_SERVER['CACHE_PASSWORD'] ) ? wp_strip_all_tags( $_SERVER['CACHE_PASSWORD'] ) : null,
-					'database' => isset( $_SERVER['CACHE_DB'] ) ? wp_strip_all_tags( $_SERVER['CACHE_DB'] ) : $database,
+					'host' => strip_tags( $_SERVER['CACHE_HOST'] ),
```
Comment (jazzsequence) [inline object-cache.php:1250]: Our linting is yelling about replacing `wp_strip_all_tags` with `strip_tags` as `strip_tags` does not strip CSS and JS in between the script and style tags. Is there a reason you've made the change?

File: object-cache.php [hunk 2]
```diff
@@ -1247,10 +1247,11 @@ public function build_client_parameters( $redis_server ) {
...
+					'port' => ! empty( $_SERVER['CACHE_PORT'] ) ? strip_tags( $_SERVER['CACHE_PORT'] ) : $port,
+					// Don't attempt to sanitize passwords as this can break authentication.
+					'auth' => ! empty( $_SERVER['CACHE_PASSWORD'] ) ? $_SERVER['CACHE_PASSWORD'] : null,
```
Comment (jazzsequence) [inline object-cache.php:1253]: Removing sanitization here is fine, but needs to be explicitly allowed.

```suggestion
					'auth' => ! empty( $_SERVER['CACHE_PASSWORD'] ) ? $_SERVER['CACHE_PASSWORD'] : null, // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
```

File: object-cache.php [hunk 3]
```diff
@@ -1275,7 +1277,7 @@ public function build_client_parameters( $redis_server ) {
 		// 1s timeout, 100ms delay between reconnections.
 
 		// merging the defaults with the original $redis_server enables any custom parameters to get sent downstream to the redis client.
-		return array_replace_recursive( $redis_server, $defaults );
+		return array_replace_recursive( $defaults, $redis_server );
```
Comment (jazzsequence) [inline object-cache.php:1280]: Can you explain what difference swapping these variables makes?

File: wp-redis.php [hunk 4]
```diff
@@ -35,21 +35,26 @@
...
 
 	if ( empty( $redis_server ) ) {
 		// Attempt to automatically load Pantheon's Redis config from the env.
 		if ( isset( $_SERVER['CACHE_HOST'] ) ) {
 			$redis_server = [
-				'host' => sanitize_text_field( $_SERVER['CACHE_HOST'] ),
-				'port' => isset( $_SERVER['CACHE_PORT'] ) ? sanitize_text_field( $_SERVER['CACHE_PORT'] ) : 6379,
-				'auth' => isset( $_SERVER['CACHE_PASSWORD'] ) ? sanitize_text_field( $_SERVER['CACHE_PASSWORD'] ) : null,
-				'database' => isset( $_SERVER['CACHE_DB'] ) ? sanitize_text_field( $_SERVER['CACHE_DB'] ) : 0,
+				'host' => strip_tags( $_SERVER['CACHE_HOST'] ),
```
Comment (jazzsequence) [inline wp-redis.php:47]: Same comments as above about `wp_strip_all_tags` vs `strip_tags` and explicitly ignoring linting rules.

**Review by jazzsequence — CHANGES_REQUESTED** [review]

File: object-cache.php (hunk 3 above)
Comment (jazzsequence) [reply object-cache.php:1280]: For future selves, RTFM: http://www.php.net/manual/en/function.array-replace-recursive.php

File: object-cache.php (hunk 1 above)
Comment (timnolte) [reply object-cache.php:1250]: Yes, see the other reported issues linked in this PR that are being fixed.

File: object-cache.php (hunk 2 above)
Comment (timnolte) [reply object-cache.php:1253]: Correct, I am aware of how to fix this to be explicitly allowed. What's interesting is that for some reason I wasn't getting flagged on these in my IDE when I made the code changes. I'll be going back and checking the linting issues as I mentioned in my earlier comment.

File: wp-redis.php [hunk 5]
```diff
@@ -73,7 +81,7 @@ function wp_redis_get_info() {
 	} else {
 		$uptime_in_days .= ' days';
 	}
-	$database  = ! empty( $redis_server['database'] ) ? $redis_server['database'] : 0;
+	$database  = ! empty( $redis_server['database'] ) ? $redis_server['database'] : $database;
```
Comment (pwtyler) [inline wp-redis.php:84]: I know this is not your code @timnolte, but raising the same thing I mentioned to Chris earlier on another ternary— with this else case, we're evaluating $database = $database. Chris thinks I just hate ternaries.
```suggestion
	if ( ! empty( $redis_server['database'] ) {
		$database = $redis_server['database'];
	}
```

**Review by jazzsequence — APPROVED** [review]

**Comment by jazzsequence** [comment]
Thanks for your patience @timnolte. We'll get a release ready for a Monday deploy.
